version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - '8000:8000'
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    command: >
      bash -c "php-fpm -D &&
               php -S 0.0.0.0:8000 -t public"
